### ISSUE TITLE
SSL certs a requirement?

### ISSUE THREAD

**Issue by ShonaliB** [West-Coast-Devops/scheduled-scaler#17]
I see [here](https://github.com/k8s-restdev/scheduled-scaler/blob/master/artifacts/kubes/scaling/deployment.yml#L26) that a volume is specified and mounted for SSL certs, in the scaling controller deployment , and wanted to verify if SSL certs are a requirement or a recommendation for this CRD on the cluster?

**Comment by ericuldall** [comment]
Hello,

Sorry for the late reply here (this repo doesn't get much issue activity). The SSL Certs are required in order for the scheduled scaler to interface with the kubernetes api on your cluster. It must be able to see when hpa's are added/updated/etc and it will also use those certs to make api calls to google cloud instance groups if you're scaling those as well.

You don't have to mount any SSL certs yourself as they will already exists in your kubernetes cluster hosts.

Please let me know if you have any other questsions.

**Comment by ericuldall** [comment]
No reply in 1 month. Going to close this for now. Please feel free to re-open if my answer was not sufficient.
