### ISSUE TITLE
Panic when the corresponding hpa resource is deleted

### ISSUE THREAD

**Issue by vnandha** [West-Coast-Devops/scheduled-scaler#19]
runtime.go:66] Observed a panic: "horizontalpodautoscalers.autoscaling \"resourcename\" not found" (horizontalpodautoscalers.autoscaling "resourcename" not found)

possibly from https://github.com/k8s-restdev/scheduled-scaler/blob/master/scaling-controller.go#L92-L95

**Comment by ericuldall** [comment]
Thanks for the PR. Everything should be updated now and new image is available at `k8srestdev/scaling:0.0.2`
