### ISSUE TITLE
Panic when processing invalid cron

### ISSUE THREAD

**Issue by Nyefan** [West-Coast-Devops/scheduled-scaler#23]
```
W0402 16:47:41.924422       1 client_config.go:529] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0402 16:47:41.938128       1 scaling-controller.go:132] SCHEDULED SCALER CREATED: application-hpa-schedule-1 -> application
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4fbbce]

goroutine 9 [running]:
k8s.restdev.com/operators/vendor/github.com/robfig/cron.(*Cron).run(0xc4200784b0)
	~/go/src/k8s.restdev.com/operators/vendor/github.com/robfig/cron/cron.go:174 +0xee
created by k8s.restdev.com/operators/vendor/github.com/robfig/cron.(*Cron).Start
	~/go/src/k8s.restdev.com/operators/vendor/github.com/robfig/cron/cron.go:144 +0x55
```

This happened when the corresponding schedule was:

```yaml
apiVersion: scaling.k8s.restdev.com/v1alpha1
kind: ScheduledScaler
metadata:
  labels:
    app: application
  name: application-hpa-schedule-1
  namespace: default
spec:
  steps:
    - maxReplicas: 100
      minReplicas: 35
      mode: range
      runat: 0 0 5 * * 1-5
    - maxReplicas: 100
      minReplicas: 7
      mode: range
      runat: 0 0 19 * * 1-7
    - maxReplicas: 100
      minReplicas: 15
      mode: range
      runat: 0 0 5 * * 6-7
  target:
    apiVersion: autoscaling/v1
    kind: HorizontalPodAutoscaler
    name: application
  timeZone: Asia/Kolkata
```

Changing the runat values to `0 0 19 * * *` and `0 0 5 * * 5-6` corrected the issue, but it would probably be best to not crash and just log the error when an incorrect schedule is created.

**Comment by ericuldall** [comment]
Yes, definitely not ideal for the process to panic in the event of this
type of user error.
I'm happy to merge a PR if you'd like to
contribute on this.

**Comment by ericuldall** [comment]
Just did a quick scan of the code and I believe we can do an initial handling in the cron service
https://github.com/West-Coast-Devops/scheduled-scaler/blob/master/pkg/services/scaling/cron/proxy.go#L15
or just above that where it's invoked...
https://github.com/West-Coast-Devops/scheduled-scaler/blob/master/scaling-controller.go#L104

**Comment by dharmab** [comment]
The least impactful workaround might be to recover from the panic by returning a cron schedule which runs every year on February 31st (i.e. never).

**Comment by scr-oath** [comment]
See #26

**Comment by dharmab** [comment]
Will there be a new release? Or should users build the image themselves?

**Comment by scr-oath** [comment]
See #27 - new image is there

**Comment by ericuldall** [comment]
@dharmab new image is in docker hub 0.0.3 and I'm working on updating the chart now.

**Comment by ericuldall** [comment]
Added to chart in #32
