### ISSUE TITLE
Build new official image 0.0.3 from #26

### ISSUE THREAD

**Issue by ericuldall** [West-Coast-Devops/scheduled-scaler#27]
Need to build a new image from PR #26 and push to official dockerhub.
Also requires chart updates to pull new image

**Comment by ericuldall** [comment]
@scr-oath I've just built a new official image including your recent changes. Would you be willing to test it?
k8srestdev/scaling:0.0.3

Would really appreciate a second pair of eyes on that 👍

**Comment by scr-oath** [comment]
Thanks! Yes, I'll reach out to get this image deployed soon.

**Comment by scr-oath** [comment]
I finally got around to testing this - and, with both a good and bad ss, I can see the bad one rejected and the good one come (every second :D )

**Comment by ericuldall** [comment]
Awesome. I'll get this updated in the chart and tagged as a stable build
