### ISSUE TITLE
README: Document location for cloning

### ISSUE THREAD

**Issue by andholix** [West-Coast-Devops/scheduled-scaler#6]
I ran through the instructions for getting started with this project, today.
Step 2b wouldn't compile properly, until I moved my cloned repo to `$GOPATH/src/k8s.restdev.com/operators`.
This might be something worth to be documented in the README.

**Comment by ericuldall** [comment]
Thanks for the note @andwun 

I'll get to this when I have some time. Feel free to send a PR if you like.

**Comment by ericuldall** [comment]
@all-contributors please add @andwun for doc
