### ISSUE TITLE
Cluster setting "Legacy authorization" seems to be required

### ISSUE THREAD

**Issue by andholix** [West-Coast-Devops/scheduled-scaler#7]
I initially tried to get the project running on a cluster with "Legacy authorization" disabled.

When starting the k8s-restdev-scaling deployment on this cluster, the following error message repeatedly appeared in the Pod's log:

```
E0319 10:44:09.099932 1 reflector.go:205] k8s.restdev.com/operators/pkg/client/informers/externalversions/factory.go:74: Failed to list *v1alpha1.ScheduledScaler: scheduledscalers.scaling.k8s.restdev.com is forbidden: User "system:serviceaccount:kube-system:default" cannot list scheduledscalers.scaling.k8s.restdev.com at the cluster scope: Unknown user "system:serviceaccount:kube-system:default"
```

Searching around a little indicated that this might be solved by enabling the cluster setting "Legacy authorization". And this did work, indeed.

I'm leaving this here for anyone who runs into the same problem.
Might also be worth documenting this as required in the README.

---

Details on my environment:
Google Kubernetes Engine
Kubernetes Version: 1.9.3-gke.0
scheduled-scaler Version: [e716936](https://github.com/k8s-restdev/scheduled-scaler/commit/e716936530aebed96bd3ec4d239476a2c4254233)

**Comment by ericuldall** [comment]
Thanks @andwun 

I agree this should be documented in the README.
